### ISSUE TITLE
Getting [King Me] advancement at wrong time

### ISSUE THREAD

**Issue by ReceptiveRaptor** [itsdinkd/AQM3#34]
I started a game, punched mahogany wood and got the [King Me] advancement.

This is my first time using the pack so forgive me if this is known.

**Comment by ReceptiveRaptor** [comment]
This just happened on another new world when getting a peach from a tree...

**Comment by itsdinkd** [comment]
Please create a new issue and use bug report template this time around to properly fill out a bug.

**Comment by itsdinkd** [comment]
Lovely Dm you sent me on discord. Just because you're slow and don't understand how to use github doesn't make it okay for you to talk your little shit. 

When you press create issues there is a nice lovely button next to Bugs that you click.  It then creates the template for you.  You avoided this and clicked start a blank issue.

Like you said,  you don't have to play my modpack.. For the love of God please do not play it. 

![Screenshot_20220205-164448_Chrome](https://user-images.githubusercontent.com/35115304/152663887-1230fb0d-7f7d-455a-b5c7-edede8e58dd7.jpg)

![Screenshot_20220205-164546_Discord](https://user-images.githubusercontent.com/35115304/152663897-82d212f4-537e-47ad-90fd-aa317c02067d.jpg)
