### ISSUE TITLE
[BUG] Immune to damage, all mobs ignore player

### ISSUE THREAD

**Issue by MoonstruckVixen** [itsdinkd/AQM3#58]
**Modpack Version**
AQM 3 1.7
**Minecraft Version**
1.18.1

**Bug**
Complete invulnerability and mob passivity, server restarting/disconnect & reconnect did not fix

**To Reproduce**
Possibly caused by being in bleedout state during server restart

**Expected behavior**
Upon reconnection, no longer in bleedout state, instead at one heart and low hunger, as though revived by another player. Mobs, including hostiles, no longer notice player, even upon being attacked. Completely immune to damage (tested with fall damage and drowning damage)

**Crash log or latest.log.log**
Log file too large for pastebin (exceeds the limit for non-pro users)

**Comment by itsdinkd** [comment]
Are you running your own server? If so, can you test by removing player revive mod to see if you re ert back go normal?

**Comment by Inyaahead** [comment]
Also had this happen, I also think its caused by the bleedout state while server restart.
The fix:
If you go into the player data for the player having this issue, check to see if invulnerable is set to 1 instead of a 0. This requires using NBT explorer.
If it's set to a 1 change to 0 and that'll solve the issue.
What we need to find out is why this changed to 1 instead of staying at 0.

**Comment by itsdinkd** [comment]
Closing due to old version
