### ISSUE TITLE
[BUG] "you can not teleport in tent" message when using enderpearls or enderian ability

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM3#88]
**Modpack Version**
1.0.2b
**Minecraft Version**
1.18.2
**Describe the bug**
Every time you use an ender pearl you get a message saying that "you can not teleport in tent" even if you're not in one.

**To Reproduce**
1. Throw ender pearl at a random location
2. "you can not teleport in tent" message pops up, and you can't use the pearl

**Expected behavior**
you should be able to use enderpearls when outside of a tent

**Comment by JessicaSkye** [comment]
This seems like an issue with the Nomadic Tents mod, it was [reported here](https://github.com/skyjay1/Nomadic-Tents/issues/69) for 1.16.5 and 1.18.2 within the past 24 hours, and has since been resolved. The fix is included in Nomadic Tents v18.2.3, updating the mod in this pack should resolve the issue.

**Comment by itsdinkd** [comment]
fixed in latest nomadic tent update
